// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVAkuZbiWya3Y4Yj6dSTSNA4yko7kicg',
    appId: '1:343526656309:android:fe654f361ccab6869e247c',
    messagingSenderId: '343526656309',
    projectId: 'travelmate-wonderpets',
    storageBucket: 'travelmate-wonderpets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_aFj6rs3P_f1d8kg2OBB8mOmtuC_N6lc',
    appId: '1:343526656309:ios:4b030a4690aa3a789e247c',
    messagingSenderId: '343526656309',
    projectId: 'travelmate-wonderpets',
    storageBucket: 'travelmate-wonderpets.appspot.com',
    iosClientId: '343526656309-8fv9dr11lc2b5tgkp3tq03h6ko5v349t.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelMate',
  );
}
